Repository ccremer/fronius-exporter, pull requests merged in 2021-08, with the labels that each got.

#42 Add support for MPPT metrics
  README.adoc
  cfg/config.go
  cfg/types.go
  main.go
  metrics.go
  pkg/fronius/symo.go
  pkg/fronius/symo_test.go
  pkg/fronius/testdata/test_archive_data.json
Labels: breaking

#43 Enable parallel scrape requests
  main.go
  metrics.go
  pkg/fronius/symo.go
  pkg/fronius/testdata/test_archive_data.json
Labels: enhancement

#44 Fix inverter label in MPPT metrics
  metrics.go
Labels: bug
